build:
  environment:
    node:
      version: v16
    php:
      version: 8
    mysql:
      version: 5.7
    hosts:
      testcraft.test: '127.0.0.1'
    variables:
      DB_DSN: 'mysql:host=localhost;port=3306;dbname=testcraft'
      DB_USER: 'root'
      DB_PASSWORD: ''
      DB_SCHEMA: ''
      DB_TABLE_PREFIX: ''
      SECURITY_KEY: 'abcde12345'
      DEFAULT_SITE_URL: 'http://testcraft.test/'
  cache:
    directories:
      - node_modules/
      - vendor/
      - ~/.composer/cache/
  dependencies:
    before:
      - mysql -uroot -e 'CREATE DATABASE testcraft'
  nodes:
    analysis:
      project_setup:
        override:
          - true
      tests:
        override:
          - php-scrutinizer-run
          - command: 'phpcs-run ./src'
            use_website_config: false
          - js-scrutinizer-run
  tests:
    override:
      - command: 'php vendor/bin/codecept run unit --coverage-xml'
        coverage:
          file: tests/_output/coverage.xml
          format: clover
checks:
  php: true
  javascript: true
coding_style:
  php: { }
filter:
  excluded_paths:
    - '*/dist/*'
    - '*/lib/*'
