<?php

/**
 * seomatic-sandbox.php
 *
 * This file exists only as a template for a sandbox configuration.
 * It does nothing on its own.
 *
 * Don't edit this file, instead copy it to 'craft/config' as 'seomatic-sandbox.php'
 * and make your changes there to override default settings.
 *
 */

use nystudio107\crafttwigsandbox\twig\BlacklistSecurityPolicy;

return [
    'class' => BlacklistSecurityPolicy::class,
    'twigTags' => [
        'autoescape',
        'block',
        'deprecated',
        'do',
        'embed',
        'extends',
        'flush',
        'from',
        'import',
        'include',
        'macro',
        'sandbox',
        'use',
        'verbatim',
        'cache',
        'css',
        'dd',
        'dump',
        'exit',
        'header',
        'hook',
        'html',
        'js',
        'namespace',
        'nav',
        'paginate',
        'redirect',
        'requireAdmin',
        'requireEdition',
        'requireGuest',
        'requireLogin',
        'requirePermission',
        'script',
        'tag',
    ],
    'twigFilters' => [
        'convert_encoding',
        'data_uri',
        'filter',
        'inky_to_html',
        'inline_css',
        'map',
        'merge',
        'reduce',
        'sort',
        'spaceless',
        'url_encode',
        'append',
        'attr',
        'base64_decode',
        'base64_encode',
        'column',
        'encenc',
        'filesize',
        'filter',
        'hash',
        'json_encode',
        'json_decode',
        'multisort',
        'namespace',
        'ns',
        'namespaceAttributes',
        'namespaceInputId',
        'namespaceInputName',
        'parseAttr',
        'parseRefs',
        'prepend',
        'removeClass',
        'where',
    ],
    'twigFunctions' => [
        'attribute',
        'block',
        'constant',
        'cycle',
        'dump',
        'html_classes',
        'parent',
        'source',
        'template_from_string',
        'actionInput',
        'alias',
        'beginBody',
        'block',
        'canCreateDrafts',
        'canDelete',
        'canDeleteForSite',
        'canDuplicate',
        'canSave',
        'canView',
        'ceil',
        'className',
        'clone',
        'combine',
        'configure',
        'constant',
        'create',
        'csrfInput',
        'dump',
        'endBody',
        'expression',
        'failMessageInput',
        'getenv',
        'gql',
        'head',
        'hiddenInput',
        'input',
        'parseBooleanEnv',
        'plugin',
        'redirectInput',
        'renderObjectTemplate',
        'source',
        'successMessageInput',
    ],
    'twigMethods' => [
    ],
    'twigProperties' => [
    ],
];
